name: itda
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.0+1
  firebase_auth:
  firebase_database: ^3.1.1
  image_picker:
  cupertino_icons: ^0.1.3
  firebase_core: any
  firebase_storage: ^3.0.8
  file_picker: 1.4.3+1
  audio_recorder:
  flutter_sound:
  intl: ^0.16.1
  path_provider: ^1.6.1
  path: ^1.6.4
  permission_handler:
  permissions_plugin:


dev_dependencies:
  flutter_test:
    sdk: flutter
  medcorder_audio:
  permission_handler:
  url_launcher: ^5.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/
    - res/
    - res/icons/ic_play.png
    - res/icons/ic_play_disabled.png
    - res/icons/2.0x/ic_play.png
    - res/icons/3.0x/ic_play.png
    - res/icons/ic_stop.png
    - res/icons/ic_stop_disabled.png
    - res/icons/2.0x/ic_stop.png
    - res/icons/3.0x/ic_stop.png
    - res/icons/ic_pause.png
    - res/icons/ic_pause_disabled.png
    - res/icons/2.0x/ic_pause.png
    - res/icons/3.0x/ic_pause.png
    - res/icons/ic_mic.png
    - res/icons/ic_mic_disabled.png
    - res/icons/2.0x/ic_mic.png
    - res/icons/3.0x/ic_mic.png
    - res/icons/ic_volume_down.png
    - res/icons/2.0x/ic_volume_down.png
    - res/icons/3.0x/ic_volume_down.png
    - res/icons/ic_volume_up.png
    - res/icons/2.0x/ic_volume_up.png
    - res/icons/3.0x/ic_volume_up.png
    - assets/samples/
    - assets/canardo.png
    - assets/
